src/ZENben/FoosballBundle/Entity/Game/Game.php
<?php

namespace ZENben\FoosballBundle\Entity\Game;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Game
 */
class Game
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var boolean
     */
    private $active;

    /**
     * @var string
     */
    private $game_form;

    /**
     * @var int
     */
    private $game_id;

    /**
     * @var string
     */
    private $name;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $updates;

    /**
     * @var integer
     */
    private $yammer_group;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $matches;
    
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->updates = new ArrayCollection();
        $this->matches = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set active
     *
     * @param  boolean $active
     * @return Game
     */
    public function setActive($active)
    {
        $this->active = $active;

        return $this;
    }

    /**
     * Get active
     *
     * @return boolean
     */
    public function getActive()
    {
        return $this->active;
    }

    /**
     * Set game_form
     *
     * @param  string $gameForm
     * @return Game
     */
    public function setGameForm($gameForm)
    {
        $this->game_form = $gameForm;

        return $this;
    }

    /**
     * Get game_form
     *
     * @return string
     */
    public function getGameForm()
    {
        return $this->game_form;
    }

    /**
     * Set game_id
     *
     * @param  \int $gameId
     * @return Game
     */
    public function setGameId($gameId)
    {
        $this->game_id = $gameId;

        return $this;
    }

    /**
     * Get game_id
     *
     * @return \int
     */
    public function getGameId()
    {
        return $this->game_id;
    }

    /**
     * Set name
     *
     * @param  string $name
     * @return Game
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @var string
     */
    private $type;


    /**
     * Set type
     *
     * @param  string $type
     * @return Game
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @var string
     */
    private $description;


    /**
     * Set description
     *
     * @param  string $description
     * @return Game
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Add updates
     *
     * @param  \ZENben\FoosballBundle\Entity\Game\GameUpdate $updates
     * @return Game
     */
    public function addUpdate(\ZENben\FoosballBundle\Entity\Game\GameUpdate $updates)
    {
        $this->updates[] = $updates;
    
        return $this;
    }

    /**
     * Remove updates
     *
     * @param \ZENben\FoosballBundle\Entity\Game\GameUpdate $updates
     */
    public function removeUpdate(\ZENben\FoosballBundle\Entity\Game\GameUpdate $updates)
    {
        $this->updates->removeElement($updates);
    }

    /**
     * Get updates
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getUpdates()
    {
        return $this->updates;
    }

    /**
     * Set yammer_group
     *
     * @param  integer $yammerGroup
     * @return Game
     */
    public function setYammerGroup($yammerGroup)
    {
        $this->yammer_group = $yammerGroup;
    
        return $this;
    }

    /**
     * Get yammer_group
     *
     * @return integer
     */
    public function getYammerGroup()
    {
        return $this->yammer_group;
    }
    
    /**
     * Add matches
     *
     * @param  \ZENben\FoosballBundle\Entity\Game\Match $matches
     * @return Game
     */
    public function addMatch(\ZENben\FoosballBundle\Entity\Game\Match $matches)
    {
        $this->matches[] = $matches;
    
        return $this;
    }

    /**
     * Remove matches
     *
     * @param \ZENben\FoosballBundle\Entity\Game\Match $matches
     */
    public function removeMatch(\ZENben\FoosballBundle\Entity\Game\Match $matches)
    {
        $this->matches->removeElement($matches);
    }

    /**
     * Get matches
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getMatches()
    {
        return $this->matches;
    }

    /**
     * Add matches
     *
     * @param  \ZENben\FoosballBundle\Entity\Game\Match $matches
     * @return Game
     */
    public function addMatche(\ZENben\FoosballBundle\Entity\Game\Match $matches)
    {
        $this->matches[] = $matches;
    
        return $this;
    }

    /**
     * Remove matches
     *
     * @param \ZENben\FoosballBundle\Entity\Game\Match $matches
     */
    public function removeMatche(\ZENben\FoosballBundle\Entity\Game\Match $matches)
    {
        $this->matches->removeElement($matches);
    }
    /**
     * @var \DateTime
     */
    private $dateStart;

    /**
     * @var \DateTime
     */
    private $dateEnded;


    /**
     * Set dateStart
     *
     * @param  \DateTime $dateStart
     * @return Game
     */
    public function setDateStart($dateStart)
    {
        $this->dateStart = $dateStart;
    
        return $this;
    }

    /**
     * Get dateStart
     *
     * @return \DateTime
     */
    public function getDateStart()
    {
        return $this->dateStart;
    }

    /**
     * Set dateEnded
     *
     * @param  \DateTime $dateEnded
     * @return Game
     */
    public function setDateEnded($dateEnded)
    {
        $this->dateEnded = $dateEnded;
    
        return $this;
    }

    /**
     * Get dateEnded
     *
     * @return \DateTime
     */
    public function getDateEnded()
    {
        return $this->dateEnded;
    }
}

src/ZENben/FoosballBundle/Entity/Game/Match.php
<?php

namespace ZENben\FoosballBundle\Entity\Game;

use Doctrine\ORM\Mapping as ORM;

/**
 * Match
 */
class Match
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var \DateTime
     */
    private $datePlayed;

    /**
     * @var integer
     */
    private $scoreRed;

    /**
     * @var integer
     */
    private $scoreBlue;

    /**
     * @var \ZENben\FoosballBundle\Entity\User\User
     */
    private $red_player;

    /**
     * @var \ZENben\FoosballBundle\Entity\User\User
     */
    private $blue_player;

    /**
     * @var \ZENben\FoosballBundle\Entity\Game\Game
     */
    private $match;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set datePlayed
     *
     * @param  \DateTime $datePlayed
     * @return Match
     */
    public function setDatePlayed($datePlayed)
    {
        $this->datePlayed = $datePlayed;

        return $this;
    }

    /**
     * Get datePlayed
     *
     * @return \DateTime
     */
    public function getDatePlayed()
    {
        return $this->datePlayed;
    }

    /**
     * Set scoreRed
     *
     * @param  integer $scoreRed
     * @return Match
     */
    public function setScoreRed($scoreRed)
    {
        $this->scoreRed = $scoreRed;

        return $this;
    }

    /**
     * Get scoreRed
     *
     * @return integer
     */
    public function getScoreRed()
    {
        return $this->scoreRed;
    }

    /**
     * Set scoreBlue
     *
     * @param  integer $scoreBlue
     * @return Match
     */
    public function setScoreBlue($scoreBlue)
    {
        $this->scoreBlue = $scoreBlue;

        return $this;
    }

    /**
     * Get scoreBlue
     *
     * @return integer
     */
    public function getScoreBlue()
    {
        return $this->scoreBlue;
    }

    /**
     * Set red_player
     *
     * @param  \ZENben\FoosballBundle\Entity\User\User $redPlayer
     * @return Match
     */
    public function setRedPlayer(\ZENben\FoosballBundle\Entity\User\User $redPlayer = null)
    {
        $this->red_player = $redPlayer;

        return $this;
    }

    /**
     * Get red_player
     *
     * @return \ZENben\FoosballBundle\Entity\User\User
     */
    public function getRedPlayer()
    {
        return $this->red_player;
    }

    /**
     * Set blue_player
     *
     * @param  \ZENben\FoosballBundle\Entity\User\User $bluePlayer
     * @return Match
     */
    public function setBluePlayer(\ZENben\FoosballBundle\Entity\User\User $bluePlayer = null)
    {
        $this->blue_player = $bluePlayer;

        return $this;
    }

    /**
     * Get blue_player
     *
     * @return \ZENben\FoosballBundle\Entity\User\User
     */
    public function getBluePlayer()
    {
        return $this->blue_player;
    }

    /**
     * @var string
     */
    private $match_id;


    /**
     * Set match_id
     *
     * @param  string $matchId
     * @return Match
     */
    public function setMatchId($matchId)
    {
        $this->match_id = $matchId;

        return $this;
    }

    /**
     * Get match_id
     *
     * @return string
     */
    public function getMatchId()
    {
        return $this->match_id;
    }

    /**
     * @var boolean
     */
    private $bye = false;


    /**
     * Set bye
     *
     * @param  boolean $bye
     * @return Match
     */
    public function setBye($bye)
    {
        $this->bye = $bye;

        return $this;
    }

    /**
     * Get bye
     *
     * @return boolean
     */
    public function getBye()
    {
        return $this->bye;
    }

    public function isPlayed()
    {
        return $this->scoreRed !== null;
    }
    
    /**
     * Set match
     *
     * @param  \ZENben\FoosballBundle\Entity\Game\Game $match
     * @return Match
     */
    public function setMatch(\ZENben\FoosballBundle\Entity\Game\Game $match = null)
    {
        $this->match = $match;
    
        return $this;
    }

    /**
     * Get match
     *
     * @return \ZENben\FoosballBundle\Entity\Game\Game
     */
    public function getMatch()
    {
        return $this->match;
    }
    /**
     * @var \ZENben\FoosballBundle\Entity\Game\Game
     */
    private $game;


    /**
     * Set game
     *
     * @param  \ZENben\FoosballBundle\Entity\Game\Game $game
     * @return Match
     */
    public function setGame(\ZENben\FoosballBundle\Entity\Game\Game $game = null)
    {
        $this->game = $game;
    
        return $this;
    }

    /**
     * Get game
     *
     * @return \ZENben\FoosballBundle\Entity\Game\Game
     */
    public function getGame()
    {
        return $this->game;
    }
}

src/ZENben/FoosballBundle/Controller/GameController.php
<?php

namespace ZENben\FoosballBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use ZENben\Bundle\YammerBundle\Service\YammerService;
use ZENben\FoosballBundle\Game\MatchesGenerator\Tournament\EliminationGenerator;

class GameController extends Controller
{
    const REASON_NOT_CURRENT_ROUND = 'not_current_round';
    const REASON_NO_WINNER = 'no_winner';

    public function indexAction($id)
    {
        $game = $this->get('game')->getGame($id);

        if ($this->getRequest()->get('gen')) {
            $this->generateNewTournament($game);
            return $this->redirect($this->generateUrl('foosball_game', ['id' => $id]));
        }

        if ($this->getRequest()->get('del')) {
            $this->deleteTournament($id);
            return $this->redirect($this->generateUrl('foosball_game', ['id' => $id]));
        }

        if ($this->getRequest()->get('reset')) {
            $this->deleteTournament($id);
            $this->generateNewTournament($game);
            return $this->redirect($this->generateUrl('foosball_game', ['id' => $id]));
        }

        return $this->render(
            'FoosballBundle:Game:index.html.twig',
            [
                'game' => $game,
                'id' => $id
            ]
        );
    }

    public function matchSaveAction($gameId, $matchId)
    {
        $scoreRed = intval($this->getRequest()->get('red'));
        $scoreBlue = intval($this->getRequest()->get('blue'));

        if (($scoreRed !== 10 && $scoreBlue !== 10) || $scoreBlue === $scoreRed) {
            return new JsonResponse(
                [
                'success' => false,
                'message' => self::REASON_NO_WINNER
                ]
            );
        }

        $match = $this->getDoctrine()->getManager()->getRepository('FoosballBundle:Game\Match')->find($matchId);

        $game = $this->get('game')->getGame($gameId);
        $currentRound = $game->getCurrentRound();
        $gameRound = $game->getRoundForMatch($match);
        if ($currentRound !== $gameRound) {
            return new JsonResponse(
                [
                'success' => false,
                'message' => self::REASON_NOT_CURRENT_ROUND
                ]
            );
        }

        $game->processScores(
            $matchId,
            [$scoreRed, $scoreBlue]
        );

        $won = 'ok';
        $user = $this->getUser();
        if ($user->getId() === $match->getBluePlayer()->getId()) {
            $won = $scoreBlue > $scoreRed ? 'won' : 'lost';
        } elseif ($user->getId() === $match->getRedPlayer()->getId()) {
            $won = $scoreRed > $scoreBlue ? 'won' : 'lost';
        }

        return new JsonResponse(
            [
            'success' => true,
            'scoreRed' => $scoreRed,
            'scoreBlue' => $scoreBlue,
            'message' => $won
            ]
        );
    }

    public function signUpAction()
    {
        $comment = $this->getRequest()->get('comment');
        $game = $this->getRequest()->get('game');

        if (strlen($comment) > 45 || strlen($comment) < 5) {
            return new JsonResponse(['success' => false]);
        }

        $em = $this->getDoctrine()->getManager();
        $user = $em->find('FoosballBundle:User\User', $this->getUser()->getId());
        $this->get('game')->getGame($game)->signUp($user, $comment);

        return new JsonResponse(
            [
            'success' => true,
            'comment' => $comment
            ]
        );
    }

    /**
     * @param $game
     * @return EliminationGenerator
     */
    private function generateNewTournament($game)
    {
        if (false === $this->get('security.context')->isGranted('ROLE_ADMIN')) {
            throw new AccessDeniedException();
        }
        $generator = new EliminationGenerator($this->getDoctrine()->getManager());
        $generator->generate($game->getParticipants(), $game);
        $this->get('game')->addUpdate(
            $game,
            'tournament.started.title',
            'tournament.started.description',
            'game.started'
        );
    }

    /**
     * @param $id
     * @throws AccessDeniedException
     * @return array
     */
    private function deleteTournament($id)
    {
        if (false === $this->get('security.context')->isGranted('ROLE_ADMIN')) {
            throw new AccessDeniedException();
        }
        $em = $this->getDoctrine()->getManager();
        $all = $em->getRepository('ZENben\FoosballBundle\Entity\Game\Match')->findByGame($id);
        foreach ($all as $match) {
            $em->remove($match);
        }
        $allUpdates = $em->getRepository('ZENben\FoosballBundle\Entity\Game\GameUpdate')->findByGame($id);
        foreach ($allUpdates as $update) {
            $em->remove($update);
        }
        $em->flush();
    }
}

src/ZENben/FoosballBundle/Resources/views/Game/gamereport.html.twig
{% if not noTitle %}
    <h3>
        <span class="match-id">{{ match.matchid|default('') }}</span>:
        <span class="red-player">{{ match.redplayer.name|default('') }}</span>
        VS.
        <span class="blue-player">{{ match.blueplayer.name|default('') }}</span>
    </h3>
{% endif %}

<div class="container">
    <div class="row">
        <div class="info info-red col-sm-6 text-center">
            <h4 class="red">{{ match.replayer.username|default('') }}</h4>
            <button class="btn btn-danger">-1</button>
            <img class="red-profile-picture profile-picture" src="{{ match.redplayer.profilepicture|default('') }}"/>
            <button class="btn btn-success">+1</button>
            <div class="score score-red"><big>5</big></div>
        </div>
        <div class="info info-blue col-sm-6 text-center">
            <h4 class="blue text-center">{{ match.replayer.username|default('') }}</h4>
            <button class="btn btn-danger">-1</button>
            <img class="blue-profile-picture profile-picture" src="{{ match.blueplayer.profilepicture|default('') }}"/>
            <button class="btn btn-success">+1</button>
            <div class="score score-blue"><big>5</big></div>
        </div>
        {#<div class="dash">—</div>#}
    </div>
</div>

src/ZENben/FoosballBundle/Resources/views/Game/index.html.twig
{% trans_default_domain 'game_index' %}
{% extends 'FoosballBundle::layout.html.twig' %}
{% block jumbotron_title %}{{ game.name }}{% endblock %}
{% block content %}
<div><a href="{{ path('foosball_homepage') }}">{{'back.to.overview'|trans}}</a></div>
    <div class="row">
        <div id="updates" class="col-md-5">
            <h2>{{ 'updates'|trans }}
                <small>{{ 'updates.sub'|trans }}</small>
            </h2>
            {% include 'FoosballBundle:Game:updates.html.twig' with { 'updates': game.updates} %}
        </div>
        {% if game.started %}
            {% if not app.user is participating(game) %}
            <div class="col-md-12">{{ 'already.started'|trans }}</div>
            {% endif %}
            <div class="col-md-6">
                <h2>{{ 'information'|trans }}
                    <small>{{ 'information.sub'|trans }}</small>
                </h2>
                {% if game.matches|length > 0 %}
                    <div id="brackets"></div>
                {% else %}
                    <div>Please wait for the admin to start the tournament</div>
                {% endif %}
                <div class="clearfix"></div>
            </div>
        {% elseif not app.user is participating(game) %}
            <div class="confirm-participation col-md-7">
                <div class="want-to-join">
                    <h2>{{ 'want.to.join'|trans }}
                        {% if not game.timeuntilstart.invert %}
                        <small>{{ 'just.x.days.left'|transchoice(game.timeuntilstart.days,{'%days%':game.timeuntilstart.days}) }}</small>
                        {% else %}
                        <small>{{ 'starts.any.moment'|trans }}</small>
                        {% endif %}
                    </h2>
                    <div class="comment-container">
                        <input maxlength="45" class="comment"
                               placeholder="{{ 'comment.placeholder'|trans }}"></textarea>
                    </div>
                    <div class="button-container clearfix">
                        <button class="btn btn-success btn-join"
                                data-url="{{ path('foosball_signup',{'game':id}) }}">{{ 'button.join'|trans }}</button>
                    </div>
                </div>
                <div class="joined" style="display: none;">
                    <h2>{{ 'thanks.for.joining'|trans }}</h2>
                    <div class="comment-container">
                        {% if not game.timeuntilstart.invert %}
                        <p>{{ 'will.begin.in'|transchoice(game.timeuntilstart.days,{'%days%':game.timeuntilstart.days}) }}</p>
                        {% else %}
                        <p>{{ 'starts.any.moment'|trans }}</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% else %}
            <div class="confirm-participation col-md-6">
                <h2>{{ 'thanks.for.joining'|trans }}</h2>
                {% if not game.timeuntilstart.invert %}
                <p>{{ 'will.begin.in'|transchoice(game.timeuntilstart.days,{'%days%':game.timeuntilstart.days}) }}</p>
                {% else %}
                <p>{{ 'starts.any.moment'|trans }}</p>
                {% endif %}
            </div>
        {% endif %}
    </div>
    <div class="modal modal-gamereport fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">{{ 'match'|trans }} <span class="title"></span>: <span class="red"></span>
                        VS. <span class="blue"></span></h4>
                </div>
                <div class="modal-body gamereport">
                    {% include 'FoosballBundle:Game:gamereport.html.twig' with {noTitle: true} %}
                </div>
                <div class="modal-footer">
                    <p class="message">
                        <span style="display: none; margin-right: 5px;"></span>
                        <button type="button" class="btn save btn-success"
                                data-url="{{ path('foosball_game_match_save', {gameId: id, matchId: '!id!'}) }}">{{ 'button.save'|trans }}</button>
                    </p>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <script type="text/javascript">
        var gameStarted = {{game.started ? 'true' : 'false'}};
        var bracketData = {
            teams: [
                {% for m in game.matches(1) %}
                [
                    {name: '{{m.redplayer.username|default('BYE')}}' },
                    {name: '{{m.blueplayer.username|default('BYE')}}' }
                ],
                {% endfor %}
            ],
            results: [
                {% for round in game.matches %}
                [
                    {% for match in round %}
                    [
                        {{match.scorered}},
                        {{match.scoreblue}},
                        {
                            id: {{match.id}},
                            matchId: {{match.matchid}},
                            red: {
                                name: '{{match.redplayer.username|default('')}}',
                                picture: '{{match.redplayer.profilepicture|default('')}}',
                                score: {{match.scorered|default('null')}}
                            },
                            blue: {
                                name: '{{match.blueplayer.username|default('')}}',
                                picture: '{{match.blueplayer.profilepicture|default('')}}',
                                score: {{match.scoreblue|default('null')}}
                            }
                        }
                    ],
                    {% endfor %}
                ],
                {% endfor %}
            ]
        }
    </script>
{% endblock %}

src/ZENben/FoosballBundle/Resources/views/Game/updates.html.twig
{% trans_default_domain 'game_updates' %}
<div class="game-updates">
    {% set lastDate = null %}
    {% for update in updates %}
        {% if update.parameters['%winner_id%'] is defined %}
            {% set user = user(update.parameters['%winner_id%']) %}
        {% elseif update.parameters['player_id'] is defined %}
            {% set user = user(update.parameters['player_id']) %}
        {% endif %}
        {% set formattedDate = update.dateCreated|localizeddate('long', 'none') %}
        {% if lastDate != formattedDate %}
            <div class="date-header">{{ formattedDate }}:</div>
            {% set lastDate = formattedDate %}
        {% endif %}
        {# New Player message#}
        {% if update.type == 'new.player' %}
            {% set icon %}
                <img src="{{ user.profilePicture }}" />
            {% endset %}
            {% set content %}
                <h4>{{ update.title|trans({ '%player%': user.username}) }}</h4>
                <p>.. {{ 'new.player.and.said'|trans }}: <em>"{{ update.description }}"</em></p>
            {% endset %}
        {# Game started #}
        {% elseif update.type == 'game.started' %}
            {% set icon %}
                <span class="glyphicon glyphicon-flag"></span>
            {% endset %}
            {% set content %}
                <h4>{{ update.title|trans(update.parameters) }}</h4>
                <p>{{ update.description|trans(update.parameters) }}</p>
            {% endset %}
        {# Match updated #}
        {% elseif update.type == 'match.updated' %}
            {% set icon %}{% endset %}
            {% set p1 = user(update.parameters['player_1_id']) %}
            {% set p2 = user(update.parameters['player_2_id']) %}
            {% set content %}
            <h4>
            {{ 'p1.won.agianst.p2'|trans({
                '%player_1_name%': p1.username,
                '%player_1_score%': update.parameters['%player_1_score%'],
                '%player_2_name%': p2.username,
                '%player_2_score%': update.parameters['%player_2_score%'],
            }) }}
            </h4>
            <div class="scoreboard">
                <div class="player1">
                    <img src="{{ p1.profilePicture }}" />
                    <div class="score">{{ update.parameters['%player_1_score%'] }}</div>
                </div>
                <div class="player2">
                    <img src="{{ p2.profilePicture }}" />
                    <div class="score">{{ update.parameters['%player_2_score%'] }}</div>
                </div>
                <div class="clearfix"></div>
            </div>
            {% endset %}
        {% elseif update.type == 'round.played' %}
            {% set icon %}
                <span class="glyphicon glyphicon-ok"></span>
            {% endset %}
            {% set content %}
                <h4>{{ update.title|trans(update.parameters) }}</h4>
                <p>{{ update.description|trans(update.parameters) }}</p>
            {% endset %}
        {% elseif update.type == 'tournament.winner' %}
            {% set icon %}
                <span class="glyphicon glyphicon-star"></span>
            {% endset %}
            {% set content %}
                <h3>{{ 'tournament.ended.title'|trans }}</h3>
                <div class="tournament-ended">
                    <p>{{ 'tournament.ended.description'|trans(update.parameters) }}</p>
                    <img class="img-responsive" src="{{ user.profilePicture }}" />
                </div>
            {% endset %}
        {# Regular updates #}
        {% else %}
            {% set icon %}{% endset %}
            {% set content %}
                <h4>{{ update.title|trans(update.parameters) }}</h4>
                <p>{{ update.description|trans(update.parameters) }}</p>
            {% endset %}
        {% endif %}
        <div class="update {{ update.type|replace({'.':'-'}) }}">
            <div class="icon-container">{{ icon }}</div>
            <div class="content-container">{{ content }}</div>
        </div>
    {% endfor %}
</div>